#!/bin/bash

xtra=$1
if [ "A${xtra}" == "Aunraid" ]; then
  xtra="-unraid"
elif [ "A${xtra}" == "A" ]; then
  xtra=""
else
  echo "$0 [unraid]"
  echo "  Push regular or unraid version to DockerHub"
  exit 1
fi

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

tag=`make -f ${SCRIPTPATH}/../Makefile | grep tag | cut -d ':' -f 2`
list=`make -f ${SCRIPTPATH}/../Makefile| grep '-' | tr -s ' ' | grep jupyter | cut -d ' ' -f 2`

# Make sure to be `docker login`-ed

echo "***** Getting list from Makefile"
todo=""
for i in $list;
do
  v=`echo $i | sed 's/-/:/'`
  t=`echo $tag | sed 's/\s+//'`

  jb=`echo $v | cut -d : -f 1`
  jt=`echo $v | cut -d : -f 2`
  jn="${jb}${xtra}:${jt}"

  cid="datamachines/${jn}-$t"
  echo " - $cid"
  todo="$todo $cid"  
done

echo ""
echo "Press Ctl+c within 5 seconds to cancel"
for i in 5 4 3 2 1; do echo -n "$i "; sleep 1; done; echo ""

for cid in $todo;
do
  echo ""
  echo ""
  echo "***** Pushing: $cid"
  echo ""
  docker push $cid || exit 1

  jb=`echo $cid | cut -d : -f 1`
  jt=`echo $cid | cut -d : -f 2`
  jn="${jb}:latest"
  docker tag $cid $jn || exit 1
  docker push $jn || exit 1
  docker rmi $jn || exit 1
done

echo "Done"